import { type FlatXoConfig } from "xo";

const xoConfig: FlatXoConfig = [
    {
        prettier: "compat",
        rules: {
            complexity: "off",
            "array-callback-return": "off",
            "arrow-body-style": "off",
            "capitalized-comments": "off",
            "func-name-matching": "off",
            "func-names": "off",
            "new-cap": "off",
            "no-else-return": "off",
            "no-implicit-coercion": "off",
            "no-negated-condition": "off",
            "no-return-await": "off",
            "no-warning-comments": "off",
            "object-shorthand": "off",
            "import-x/extensions": "off",
            "import-x/no-unassigned-import": "off",
            "import-x/order": "off",
            "n/no-path-concat": "off",
            "n/prefer-global/process": "off",
            "promise/prefer-await-to-then": "off",
            "@stylistic/padding-line-between-statements": "off",
            "@typescript-eslint/array-type": "off",
            "@typescript-eslint/consistent-type-definitions": "off",
            "@typescript-eslint/consistent-type-imports": "off",
            "@typescript-eslint/default-param-last": "off",
            "@typescript-eslint/naming-convention": "off",
            "@typescript-eslint/no-confusing-void-expression": "off",
            "@typescript-eslint/no-deprecated": "off",
            "@typescript-eslint/no-duplicate-type-constituents": "off",
            "@typescript-eslint/no-empty-function": "off",
            "@typescript-eslint/no-floating-promises": "off",
            "@typescript-eslint/no-inferrable-types": "off",
            "@typescript-eslint/no-redeclare": "off",
            "@typescript-eslint/no-restricted-types": "off",
            "@typescript-eslint/no-unnecessary-type-arguments": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/promise-function-async": "off",
            "@typescript-eslint/return-await": "off",
            "@typescript-eslint/switch-exhaustiveness-check": "off",
            "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
            "unicorn/explicit-length-check": "off",
            "unicorn/filename-case": "off",
            "unicorn/new-for-builtins": "off",
            "unicorn/no-array-callback-reference": "off",
            "unicorn/no-array-reduce": "off",
            "unicorn/no-array-for-each": "off",
            "unicorn/no-negated-condition": "off",
            "unicorn/prevent-abbreviations": "off",
            "unicorn/prefer-array-some": "off",
            "unicorn/prefer-dom-node-append": "off",
            "unicorn/prefer-global-this": "off",
            "unicorn/prefer-logical-operator-over-ternary": "off",
            "unicorn/prefer-module": "off",
            "unicorn/prefer-negative-index": "off",
            "unicorn/prefer-node-protocol": "off",
            "unicorn/prefer-number-properties": "off",
            "unicorn/prefer-set-has": "off",
            "unicorn/prefer-spread": "off",
            "unicorn/prefer-query-selector": "off",
            "unicorn/require-array-join-separator": "off",
            "unicorn/switch-case-braces": "off",
        },
    },
];

export default xoConfig;
