export const sides = ["Free", "Shadow"] as const;

export const victoryTypes = ["Ring", "Military", "Concession"] as const;

export const matchTypes = ["Rated", "Unrated"] as const;

export const competitionTypes = ["League", "Tournament"] as const;

export const expansionLeagues = [
    "LoMELeague",
    "WoMELeague",
    "SuperLeague",
    "TTSLeague",
] as const;

export const leagues = ["GeneralLeague", ...expansionLeagues] as const;

export const leagueTiers = ["Tier1", "Tier2", "Tier3"] as const;

export const expansions = [
    "LoME",
    "WoME",
    "KoME",
    "Cities",
    "FateOfErebor",
    "Treebeard",
] as const;

export const strongholds = [
    "Rivendell",
    "GreyHavens",
    "HelmsDeep",
    "Lorien",
    "WoodlandRealm",
    "MinasTirith",
    "DolAmroth",
    "Shire",
    "Edoras",
    "Dale",
    "Pelargir",
    "EredLuin",
    "IronHills",
    "MountGundabad",
    "Moria",
    "DolGuldur",
    "Orthanc",
    "Morannon",
    "BaradDur",
    "MinasMorgul",
    "Umbar",
    "Angmar",
    "FarHarad",
    "SouthRhun",
    "Erebor",
] as const;

export const optionalFormFields = ["rid", "timestamp", "logFile"] as const;

export const optionalPayloadFields = [
    "competition",
    "league",
    "expansions",
    "treebeard",
    "actionTokens",
    "dwarvenRings",
    "mordor",
    "aragornTurn",
    "strongholds",
    "comment",
] as const;

export const optionalFields = [
    ...optionalFormFields,
    ...optionalPayloadFields,
] as const;

export const payloadFields = [
    ...optionalPayloadFields,
    "winner",
    "loser",
    "side",
    "victory",
    "match",
    "turns",
    "corruption",
    "initialEyes",
    "interestRating",
] as const;

export const optionalPlayerEditFields = ["country"] as const;

export const serverValidationErrors = [
    "VictoryConditionConflictSPRV",
    "VictoryConditionConflictFPRV",
    "VictoryConditionConflictSPMV",
    "VictoryConditionConflictFPMV",
    "VictoryConditionConflictConcession",
    "NoVictoryConditionMet",
    "InvalidSPMV",
    "InvalidFPMV",
    "InvalidSPRV",
    "InvalidFPRV",
    "CompetitionMismatch",
    "LeagueExpansionMismatch",
    "TreebeardExpansionMismatch",
    "TurnsOutOfRange",
    "CorruptionOutOfRange",
    "MordorOutOfRange",
    "InitialEyesOutOfRange",
    "InterestRatingOutOfRange",
    "InvalidStronghold",
] as const;

export const playerStates = ["Active", "Inactive"] as const;

export enum ErrorMessage {
    Default = "Something went wrong. Please contact an admin for assistance.",
    NotAuthorized = "You cannot pass! If you're an administrator, your session may have expired. Please log in and try again.",
    NotAuthorizedStatus = "You cannot pass!",
    UnknownAuthStatus = "Sign-in unavailable",
    Required = "Required",
    OnSubmit = "Could not submit, please resolve errors",
    MissingPlayerName = "This player does not exist in the database. Unless it's a new player, please check the spelling.",
    ExistingPlayerRequired = "Must choose an existing player",
}

export const INFINITE = 100;
export const LEADERBOARD_START_YEAR = 2023;
export const LEAGUE_START_YEAR = 2025;
export const MAX_GAME_LOG_SIZE_MB = 1;
export const MAX_GAME_LOG_SIZE_BYTES = MAX_GAME_LOG_SIZE_MB * 1024 * 1024;

export const COUNTRY_FLAGS = {
    Andorra: "🇦🇩",
    "United Arab Emirates": "🇦🇪",
    Afghanistan: "🇦🇫",
    "Antigua and Barbuda": "🇦🇬",
    Anguilla: "🇦🇮",
    Albania: "🇦🇱",
    Armenia: "🇦🇲",
    Angola: "🇦🇴",
    Antarctica: "🇦🇶",
    Argentina: "🇦🇷",
    "American Samoa": "🇦🇸",
    Austria: "🇦🇹",
    Australia: "🇦🇺",
    Aruba: "🇦🇼",
    "Åland Islands": "🇦🇽",
    Azerbaijan: "🇦🇿",
    Bosnia: "🇧🇦",
    Barbados: "🇧🇧",
    Bangladesh: "🇧🇩",
    Belgium: "🇧🇪",
    "Burkina Faso": "🇧🇫",
    Bulgaria: "🇧🇬",
    Bahrain: "🇧🇭",
    Burundi: "🇧🇮",
    Benin: "🇧🇯",
    "Saint Barthélemy": "🇧🇱",
    Bermuda: "🇧🇲",
    "Brunei Darussalam": "🇧🇳",
    Bolivia: "🇧🇴",
    "Bonaire, Sint Eustatius and Saba": "🇧🇶",
    Brazil: "🇧🇷",
    Bahamas: "🇧🇸",
    Bhutan: "🇧🇹",
    "Bouvet Island": "🇧🇻",
    Botswana: "🇧🇼",
    Belarus: "🇧🇾",
    Belize: "🇧🇿",
    Canada: "🇨🇦",
    "Cocos (Keeling) Islands": "🇨🇨",
    "Democratic Republic of the Congo": "🇨🇩",
    "Central African Republic": "🇨🇫",
    "Republic of the Congo": "🇨🇬",
    Switzerland: "🇨🇭",
    "Côte D'Ivoire": "🇨🇮",
    "Cook Islands": "🇨🇰",
    Chile: "🇨🇱",
    Cameroon: "🇨🇲",
    China: "🇨🇳",
    Colombia: "🇨🇴",
    "Costa Rica": "🇨🇷",
    Cuba: "🇨🇺",
    "Cape Verde": "🇨🇻",
    Curaçao: "🇨🇼",
    "Christmas Island": "🇨🇽",
    Cyprus: "🇨🇾",
    "Czech Republic": "🇨🇿",
    Germany: "🇩🇪",
    Djibouti: "🇩🇯",
    Denmark: "🇩🇰",
    Dominica: "🇩🇲",
    "Dominican Republic": "🇩🇴",
    Algeria: "🇩🇿",
    Ecuador: "🇪🇨",
    Estonia: "🇪🇪",
    Egypt: "🇪🇬",
    "Western Sahara": "🇪🇭",
    Eritrea: "🇪🇷",
    Spain: "🇪🇸",
    Ethiopia: "🇪🇹",
    Finland: "🇫🇮",
    Fiji: "🇫🇯",
    "Falkland Islands (Malvinas)": "🇫🇰",
    Micronesia: "🇫🇲",
    "Faroe Islands": "🇫🇴",
    France: "🇫🇷",
    Gabon: "🇬🇦",
    Grenada: "🇬🇩",
    Georgia: "🇬🇪",
    "French Guiana": "🇬🇫",
    Guernsey: "🇬🇬",
    Ghana: "🇬🇭",
    Gibraltar: "🇬🇮",
    Greenland: "🇬🇱",
    Gambia: "🇬🇲",
    Guinea: "🇬🇳",
    Guadeloupe: "🇬🇵",
    "Equatorial Guinea": "🇬🇶",
    Greece: "🇬🇷",
    "South Georgia": "🇬🇸",
    Guatemala: "🇬🇹",
    Guam: "🇬🇺",
    "Guinea-Bissau": "🇬🇼",
    Guyana: "🇬🇾",
    "Hong Kong": "🇭🇰",
    "Heard Island and Mcdonald Islands": "🇭🇲",
    Honduras: "🇭🇳",
    Croatia: "🇭🇷",
    Haiti: "🇭🇹",
    Hungary: "🇭🇺",
    Indonesia: "🇮🇩",
    Ireland: "🇮🇪",
    Israel: "🇮🇱",
    "Isle of Man": "🇮🇲",
    India: "🇮🇳",
    "British Indian Ocean Territory": "🇮🇴",
    Iraq: "🇮🇶",
    Iran: "🇮🇷",
    Iceland: "🇮🇸",
    Italy: "🇮🇹",
    Jersey: "🇯🇪",
    Jamaica: "🇯🇲",
    Jordan: "🇯🇴",
    Japan: "🇯🇵",
    Kenya: "🇰🇪",
    Kyrgyzstan: "🇰🇬",
    Cambodia: "🇰🇭",
    Kiribati: "🇰🇮",
    Comoros: "🇰🇲",
    "Saint Kitts and Nevis": "🇰🇳",
    "North Korea": "🇰🇵",
    "South Korea": "🇰🇷",
    Kuwait: "🇰🇼",
    "Cayman Islands": "🇰🇾",
    Kazakhstan: "🇰🇿",
    "Lao People's Democratic Republic": "🇱🇦",
    Lebanon: "🇱🇧",
    "Saint Lucia": "🇱🇨",
    Liechtenstein: "🇱🇮",
    "Sri Lanka": "🇱🇰",
    Liberia: "🇱🇷",
    Lesotho: "🇱🇸",
    Lithuania: "🇱🇹",
    Luxembourg: "🇱🇺",
    Latvia: "🇱🇻",
    Libya: "🇱🇾",
    Morocco: "🇲🇦",
    Monaco: "🇲🇨",
    Moldova: "🇲🇩",
    Montenegro: "🇲🇪",
    "Saint Martin (French Part)": "🇲🇫",
    Madagascar: "🇲🇬",
    "Marshall Islands": "🇲🇭",
    Macedonia: "🇲🇰",
    Mali: "🇲🇱",
    Myanmar: "🇲🇲",
    Mongolia: "🇲🇳",
    Macao: "🇲🇴",
    "Northern Mariana Islands": "🇲🇵",
    Martinique: "🇲🇶",
    Mauritania: "🇲🇷",
    Montserrat: "🇲🇸",
    Malta: "🇲🇹",
    Mauritius: "🇲🇺",
    Maldives: "🇲🇻",
    Malawi: "🇲🇼",
    Mexico: "🇲🇽",
    Malaysia: "🇲🇾",
    Mozambique: "🇲🇿",
    Namibia: "🇳🇦",
    "New Caledonia": "🇳🇨",
    Niger: "🇳🇪",
    "Norfolk Island": "🇳🇫",
    Nigeria: "🇳🇬",
    Nicaragua: "🇳🇮",
    Netherlands: "🇳🇱",
    Norway: "🇳🇴",
    Nepal: "🇳🇵",
    Nauru: "🇳🇷",
    Niue: "🇳🇺",
    "New Zealand": "🇳🇿",
    Oman: "🇴🇲",
    Panama: "🇵🇦",
    Peru: "🇵🇪",
    "French Polynesia": "🇵🇫",
    "Papua New Guinea": "🇵🇬",
    Philippines: "🇵🇭",
    Pakistan: "🇵🇰",
    Poland: "🇵🇱",
    "Saint Pierre and Miquelon": "🇵🇲",
    Pitcairn: "🇵🇳",
    "Puerto Rico": "🇵🇷",
    "Palestinian Territory": "🇵🇸",
    Portugal: "🇵🇹",
    Palau: "🇵🇼",
    Paraguay: "🇵🇾",
    Qatar: "🇶🇦",
    Réunion: "🇷🇪",
    Romania: "🇷🇴",
    Serbia: "🇷🇸",
    Russia: "🇷🇺",
    Rwanda: "🇷🇼",
    "Saudi Arabia": "🇸🇦",
    "Solomon Islands": "🇸🇧",
    Seychelles: "🇸🇨",
    Sudan: "🇸🇩",
    Sweden: "🇸🇪",
    Singapore: "🇸🇬",
    "Saint Helena, Ascension and Tristan Da Cunha": "🇸🇭",
    Slovenia: "🇸🇮",
    "Svalbard and Jan Mayen": "🇸🇯",
    Slovakia: "🇸🇰",
    "Sierra Leone": "🇸🇱",
    "San Marino": "🇸🇲",
    Senegal: "🇸🇳",
    Somalia: "🇸🇴",
    Suriname: "🇸🇷",
    "South Sudan": "🇸🇸",
    "Sao Tome and Principe": "🇸🇹",
    "El Salvador": "🇸🇻",
    "Sint Maarten (Dutch Part)": "🇸🇽",
    "Syrian Arab Republic": "🇸🇾",
    Swaziland: "🇸🇿",
    "Turks and Caicos Islands": "🇹🇨",
    Chad: "🇹🇩",
    "French Southern Territories": "🇹🇫",
    Togo: "🇹🇬",
    Thailand: "🇹🇭",
    Tajikistan: "🇹🇯",
    Tokelau: "🇹🇰",
    "Timor-Leste": "🇹🇱",
    Turkmenistan: "🇹🇲",
    Tunisia: "🇹🇳",
    Tonga: "🇹🇴",
    Turkey: "🇹🇷",
    "Trinidad and Tobago": "🇹🇹",
    Tuvalu: "🇹🇻",
    Taiwan: "🇹🇼",
    Tanzania: "🇹🇿",
    Ukraine: "🇺🇦",
    "United Kingdom": "🇬🇧",
    Uganda: "🇺🇬",
    "United States Minor Outlying Islands": "🇺🇲",
    "United States of America": "🇺🇸",
    Uruguay: "🇺🇾",
    Uzbekistan: "🇺🇿",
    "Vatican City": "🇻🇦",
    "Saint Vincent and The Grenadines": "🇻🇨",
    Venezuela: "🇻🇪",
    "Virgin Islands, British": "🇻🇬",
    "Virgin Islands, U.S.": "🇻🇮",
    Vietnam: "🇻🇳",
    Vanuatu: "🇻🇺",
    "Wallis and Futuna": "🇼🇫",
    Samoa: "🇼🇸",
    Yemen: "🇾🇪",
    Mayotte: "🇾🇹",
    "South Africa": "🇿🇦",
    Zambia: "🇿🇲",
    Zimbabwe: "🇿🇼",
    Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
};
