import scotlandFlagSrc from "./assets/scotland-flag.png";
import walesFlagSrc from "./assets/wales-flag.png";

export const sides = ["Free", "Shadow"] as const;

export const victoryTypes = ["Ring", "Military", "Concession"] as const;

export const matchTypes = ["Rated", "Unrated"] as const;

export const competitionTypes = ["League", "Tournament"] as const;

export const expansionLeagues = [
    "LoMELeague",
    "WoMELeague",
    "SuperLeague",
    "TTSLeague",
] as const;

export const leagues = ["GeneralLeague", ...expansionLeagues] as const;

export const leagueTiers = ["Tier1", "Tier2", "Tier3"] as const;

export const expansions = [
    "LoME",
    "WoME",
    "KoME",
    "Cities",
    "FateOfErebor",
    "Treebeard",
] as const;

export const strongholds = [
    "Rivendell",
    "GreyHavens",
    "HelmsDeep",
    "Lorien",
    "WoodlandRealm",
    "MinasTirith",
    "DolAmroth",
    "Shire",
    "Edoras",
    "Dale",
    "Pelargir",
    "EredLuin",
    "IronHills",
    "MountGundabad",
    "Moria",
    "DolGuldur",
    "Orthanc",
    "Morannon",
    "BaradDur",
    "MinasMorgul",
    "Umbar",
    "Angmar",
    "FarHarad",
    "SouthRhun",
    "Erebor",
] as const;

export const optionalFormFields = ["rid", "timestamp", "logFile"] as const;

export const optionalPayloadFields = [
    "competition",
    "league",
    "expansions",
    "treebeard",
    "actionTokens",
    "dwarvenRings",
    "mordor",
    "aragornTurn",
    "strongholds",
    "comment",
] as const;

export const optionalFields = [
    ...optionalFormFields,
    ...optionalPayloadFields,
] as const;

export const payloadFields = [
    ...optionalPayloadFields,
    "winner",
    "loser",
    "side",
    "victory",
    "match",
    "turns",
    "corruption",
    "initialEyes",
    "interestRating",
] as const;

export const optionalPlayerEditFields = ["country"] as const;

export const serverValidationErrors = [
    "VictoryConditionConflictSPRV",
    "VictoryConditionConflictFPRV",
    "VictoryConditionConflictSPMV",
    "VictoryConditionConflictFPMV",
    "VictoryConditionConflictConcession",
    "NoVictoryConditionMet",
    "InvalidSPMV",
    "InvalidFPMV",
    "InvalidSPRV",
    "InvalidFPRV",
    "CompetitionMismatch",
    "LeagueExpansionMismatch",
    "TreebeardExpansionMismatch",
    "TurnsOutOfRange",
    "CorruptionOutOfRange",
    "MordorOutOfRange",
    "InitialEyesOutOfRange",
    "InterestRatingOutOfRange",
    "InvalidStronghold",
] as const;

export const playerStates = ["Active", "Inactive"] as const;

export enum ErrorMessage {
    Default = "Something went wrong. Please contact an admin for assistance.",
    NotAuthorized = "You cannot pass! If you're an administrator, your session may have expired. Please log in and try again.",
    NotAuthorizedStatus = "You cannot pass!",
    UnknownAuthStatus = "Sign-in unavailable",
    Required = "Required",
    OnSubmit = "Could not submit, please resolve errors",
    MissingPlayerName = "This player does not exist in the database. Unless it's a new player, please check the spelling.",
    ExistingPlayerRequired = "Must choose an existing player",
}

export const INFINITE = 100;
export const LEADERBOARD_START_YEAR = 2023;
export const LEAGUE_START_YEAR = 2025;
export const MAX_GAME_LOG_SIZE_MB = 1;
export const MAX_GAME_LOG_SIZE_BYTES = MAX_GAME_LOG_SIZE_MB * 1024 * 1024;

export const COUNTRIES_DATA = {
    "Ascension Island": { code: "AC", src: null },
    Andorra: { code: "AD", src: null },
    "United Arab Emirates": { code: "AE", src: null },
    Afghanistan: { code: "AF", src: null },
    "Antigua and Barbuda": { code: "AG", src: null },
    Anguilla: { code: "AI", src: null },
    Albania: { code: "AL", src: null },
    Armenia: { code: "AM", src: null },
    Angola: { code: "AO", src: null },
    Antarctica: { code: "AQ", src: null },
    Argentina: { code: "AR", src: null },
    "American Samoa": { code: "AS", src: null },
    Austria: { code: "AT", src: null },
    Australia: { code: "AU", src: null },
    Aruba: { code: "AW", src: null },
    "Åland Islands": { code: "AX", src: null },
    Azerbaijan: { code: "AZ", src: null },
    Bosnia: { code: "BA", src: null },
    Barbados: { code: "BB", src: null },
    Bangladesh: { code: "BD", src: null },
    Belgium: { code: "BE", src: null },
    "Burkina Faso": { code: "BF", src: null },
    Bulgaria: { code: "BG", src: null },
    Bahrain: { code: "BH", src: null },
    Burundi: { code: "BI", src: null },
    Benin: { code: "BJ", src: null },
    "Saint Barthélemy": { code: "BL", src: null },
    Bermuda: { code: "BM", src: null },
    Brunei: { code: "BN", src: null },
    Bolivia: { code: "BO", src: null },
    "Bonaire, Sint Eustatius and Saba": { code: "BQ", src: null },
    Brazil: { code: "BR", src: null },
    Bahamas: { code: "BS", src: null },
    Bhutan: { code: "BT", src: null },
    "Bouvet Island": { code: "BV", src: null },
    Botswana: { code: "BW", src: null },
    Belarus: { code: "BY", src: null },
    Belize: { code: "BZ", src: null },
    Canada: { code: "CA", src: null },
    "Cocos (Keeling) Islands": { code: "CC", src: null },
    "Democratic Republic of the Congo": { code: "CD", src: null },
    "Central African Republic": { code: "CF", src: null },
    "Republic of the Congo": { code: "CG", src: null },
    Switzerland: { code: "CH", src: null },
    "Côte d'Ivoire": { code: "CI", src: null },
    "Cook Islands": { code: "CK", src: null },
    Chile: { code: "CL", src: null },
    Cameroon: { code: "CM", src: null },
    China: { code: "CN", src: null },
    Colombia: { code: "CO", src: null },
    "Clipperton Island": { code: "CP", src: null },
    Sark: { code: "CQ", src: null },
    "Costa Rica": { code: "CR", src: null },
    Cuba: { code: "CU", src: null },
    "Cabo Verde": { code: "CV", src: null },
    Curaçao: { code: "CW", src: null },
    "Christmas Island": { code: "CX", src: null },
    Cyprus: { code: "CY", src: null },
    "Czech Republic": { code: "CZ", src: null },
    Germany: { code: "DE", src: null },
    "Diego Garcia": { code: "DG", src: null },
    Djibouti: { code: "DJ", src: null },
    Denmark: { code: "DK", src: null },
    Dominica: { code: "DM", src: null },
    "Dominican Republic": { code: "DO", src: null },
    Algeria: { code: "DZ", src: null },
    "Ceuta and Melilla": { code: "EA", src: null },
    Ecuador: { code: "EC", src: null },
    Estonia: { code: "EE", src: null },
    Egypt: { code: "EG", src: null },
    "Western Sahara": { code: "EH", src: null },
    Eritrea: { code: "ER", src: null },
    Spain: { code: "ES", src: null },
    Ethiopia: { code: "ET", src: null },
    "European Union": { code: "EU", src: null },
    Finland: { code: "FI", src: null },
    Fiji: { code: "FJ", src: null },
    "Falkland Islands": { code: "FK", src: null },
    Micronesia: { code: "FM", src: null },
    "Faroe Islands": { code: "FO", src: null },
    France: { code: "FR", src: null },
    Gabon: { code: "GA", src: null },
    "United Kingdom": { code: "GB", src: null },
    Grenada: { code: "GD", src: null },
    Georgia: { code: "GE", src: null },
    "French Guiana": { code: "GF", src: null },
    Guernsey: { code: "GG", src: null },
    Ghana: { code: "GH", src: null },
    Gibraltar: { code: "GI", src: null },
    Greenland: { code: "GL", src: null },
    Gambia: { code: "GM", src: null },
    Guinea: { code: "GN", src: null },
    Guadeloupe: { code: "GP", src: null },
    "Equatorial Guinea": { code: "GQ", src: null },
    Greece: { code: "GR", src: null },
    "South Georgia and the South Sandwich Islands": { code: "GS", src: null },
    Guatemala: { code: "GT", src: null },
    Guam: { code: "GU", src: null },
    "Guinea-Bissau": { code: "GW", src: null },
    Guyana: { code: "GY", src: null },
    "Hong Kong": { code: "HK", src: null },
    "Heard and McDonald Islands": { code: "HM", src: null },
    Honduras: { code: "HN", src: null },
    Croatia: { code: "HR", src: null },
    Haiti: { code: "HT", src: null },
    Hungary: { code: "HU", src: null },
    "Canary Islands": { code: "IC", src: null },
    Indonesia: { code: "ID", src: null },
    Ireland: { code: "IE", src: null },
    Israel: { code: "IL", src: null },
    "Isle of Man": { code: "IM", src: null },
    India: { code: "IN", src: null },
    "British Indian Ocean Territory": { code: "IO", src: null },
    Iraq: { code: "IQ", src: null },
    Iran: { code: "IR", src: null },
    Iceland: { code: "IS", src: null },
    Italy: { code: "IT", src: null },
    Jersey: { code: "JE", src: null },
    Jamaica: { code: "JM", src: null },
    Jordan: { code: "JO", src: null },
    Japan: { code: "JP", src: null },
    Kenya: { code: "KE", src: null },
    Kyrgyzstan: { code: "KG", src: null },
    Cambodia: { code: "KH", src: null },
    Kiribati: { code: "KI", src: null },
    Comoros: { code: "KM", src: null },
    "Saint Kitts and Nevis": { code: "KN", src: null },
    "North Korea": { code: "KP", src: null },
    "South Korea": { code: "KR", src: null },
    Kuwait: { code: "KW", src: null },
    "Cayman Islands": { code: "KY", src: null },
    Kazakhstan: { code: "KZ", src: null },
    Laos: { code: "LA", src: null },
    Lebanon: { code: "LB", src: null },
    "Saint Lucia": { code: "LC", src: null },
    Liechtenstein: { code: "LI", src: null },
    "Sri Lanka": { code: "LK", src: null },
    Liberia: { code: "LR", src: null },
    Lesotho: { code: "LS", src: null },
    Lithuania: { code: "LT", src: null },
    Luxembourg: { code: "LU", src: null },
    Latvia: { code: "LV", src: null },
    Libya: { code: "LY", src: null },
    Morocco: { code: "MA", src: null },
    Monaco: { code: "MC", src: null },
    Moldova: { code: "MD", src: null },
    Montenegro: { code: "ME", src: null },
    "Saint Martin": { code: "MF", src: null },
    Madagascar: { code: "MG", src: null },
    "Marshall Islands": { code: "MH", src: null },
    "North Macedonia": { code: "MK", src: null },
    Mali: { code: "ML", src: null },
    Myanmar: { code: "MM", src: null },
    Mongolia: { code: "MN", src: null },
    Macau: { code: "MO", src: null },
    "Northern Mariana Islands": { code: "MP", src: null },
    Martinique: { code: "MQ", src: null },
    Mauritania: { code: "MR", src: null },
    Montserrat: { code: "MS", src: null },
    Malta: { code: "MT", src: null },
    Mauritius: { code: "MU", src: null },
    Maldives: { code: "MV", src: null },
    Malawi: { code: "MW", src: null },
    Mexico: { code: "MX", src: null },
    Malaysia: { code: "MY", src: null },
    Mozambique: { code: "MZ", src: null },
    Namibia: { code: "NA", src: null },
    "New Caledonia": { code: "NC", src: null },
    Niger: { code: "NE", src: null },
    "Norfolk Island": { code: "NF", src: null },
    Nigeria: { code: "NG", src: null },
    Nicaragua: { code: "NI", src: null },
    Netherlands: { code: "NL", src: null },
    Norway: { code: "NO", src: null },
    Nepal: { code: "NP", src: null },
    Nauru: { code: "NR", src: null },
    Niue: { code: "NU", src: null },
    "New Zealand": { code: "NZ", src: null },
    Oman: { code: "OM", src: null },
    Panama: { code: "PA", src: null },
    Peru: { code: "PE", src: null },
    "French Polynesia": { code: "PF", src: null },
    "Papua New Guinea": { code: "PG", src: null },
    Philippines: { code: "PH", src: null },
    Pakistan: { code: "PK", src: null },
    Poland: { code: "PL", src: null },
    "Saint Pierre and Miquelon": { code: "PM", src: null },
    "Pitcairn Islands": { code: "PN", src: null },
    "Puerto Rico": { code: "PR", src: null },
    Palestine: { code: "PS", src: null },
    Portugal: { code: "PT", src: null },
    Palau: { code: "PW", src: null },
    Paraguay: { code: "PY", src: null },
    Qatar: { code: "QA", src: null },
    Réunion: { code: "RE", src: null },
    Romania: { code: "RO", src: null },
    Serbia: { code: "RS", src: null },
    Russia: { code: "RU", src: null },
    Rwanda: { code: "RW", src: null },
    "Saudi Arabia": { code: "SA", src: null },
    "Solomon Islands": { code: "SB", src: null },
    Seychelles: { code: "SC", src: null },
    Sudan: { code: "SD", src: null },
    Sweden: { code: "SE", src: null },
    Singapore: { code: "SG", src: null },
    "Saint Helena": { code: "SH", src: null },
    Slovenia: { code: "SI", src: null },
    "Svalbard and Jan Mayen": { code: "SJ", src: null },
    Slovakia: { code: "SK", src: null },
    "Sierra Leone": { code: "SL", src: null },
    "San Marino": { code: "SM", src: null },
    Senegal: { code: "SN", src: null },
    Somalia: { code: "SO", src: null },
    Suriname: { code: "SR", src: null },
    "South Sudan": { code: "SS", src: null },
    "São Tomé and Príncipe": { code: "ST", src: null },
    "El Salvador": { code: "SV", src: null },
    "Sint Maarten": { code: "SX", src: null },
    Syria: { code: "SY", src: null },
    Swaziland: { code: "SZ", src: null },
    "Tristan da Cunha": { code: "TA", src: null },
    "Turks and Caicos Islands": { code: "TC", src: null },
    Chad: { code: "TD", src: null },
    "French Southern Territories": { code: "TF", src: null },
    Togo: { code: "TG", src: null },
    Thailand: { code: "TH", src: null },
    Tajikistan: { code: "TJ", src: null },
    Tokelau: { code: "TK", src: null },
    "Timor-Leste": { code: "TL", src: null },
    Turkmenistan: { code: "TM", src: null },
    Tunisia: { code: "TN", src: null },
    Tonga: { code: "TO", src: null },
    Turkey: { code: "TR", src: null },
    "Trinidad and Tobago": { code: "TT", src: null },
    Tuvalu: { code: "TV", src: null },
    Taiwan: { code: "TW", src: null },
    Tanzania: { code: "TZ", src: null },
    Ukraine: { code: "UA", src: null },
    Uganda: { code: "UG", src: null },
    "U.S. Minor Outlying Islands": { code: "UM", src: null },
    "United Nations": { code: "UN", src: null },
    "United States of America": { code: "US", src: null },
    Uruguay: { code: "UY", src: null },
    Uzbekistan: { code: "UZ", src: null },
    "Vatican City": { code: "VA", src: null },
    "Saint Vincent and the Grenadines": { code: "VC", src: null },
    Venezuela: { code: "VE", src: null },
    "Virgin Islands (British)": { code: "VG", src: null },
    "Virgin Islands (U.S.)": { code: "VI", src: null },
    Vietnam: { code: "VN", src: null },
    Vanuatu: { code: "VU", src: null },
    "Wallis and Futuna": { code: "WF", src: null },
    Samoa: { code: "WS", src: null },
    Kosovo: { code: "XK", src: null },
    Yemen: { code: "YE", src: null },
    Mayotte: { code: "YT", src: null },
    "South Africa": { code: "ZA", src: null },
    Zambia: { code: "ZM", src: null },
    Zimbabwe: { code: "ZW", src: null },
    Scotland: { code: null, src: scotlandFlagSrc },
    Wales: { code: null, src: walesFlagSrc },
};
